#!/bin/bash

for file in $(git diff --name-only --staged --diff-filter=d | sort | uniq | grep -E "(ex|exs)")
do
  if [ -f "$file" ]
  then
    echo "[pre-commit] Formatting $file"
    mix format $file
    git add $file
  fi
done
